### ISSUE TITLE
Autoconvert should detect ASCII binary without preceding 0

### ISSUE THREAD

**Issue by beckbria** [kfarnung/puzzle-lib#71]
Repro steps:

1) Go to autoconvert
2) Enter "1000011 1101111"

Expected: "Co"
Actual: Nothing

**Comment by sjenks** [comment]
PR our for 7 digit ascii, but short 5 bit binary is ambiguous 
(eg 10 could be binary 'B' or ordinal J)

**Comment by kfarnung** [comment]
Would it be reasonable to try and interpret the entire string as the same encoding? Then you could use more a more heuristic approach and then display all possible encodings for the entire string. Maybe discount any interpretations where none of the encodings match a letter?

**Comment by sjenks** [comment]
I think what you're asking for is 'force consistent encoding'?

**Comment by kfarnung** [comment]
The problem is that I think that behavior should be default. I can't think of a puzzle where I input a stream of numbers where each one has a different encoding.

**Comment by sjenks** [comment]
Seems reasonable. It shouldn't be a big change, but I'm not likely to be able to do it for another day or two.


________________________________

**Comment by beckbria** [comment]
What I want (feature work outside this bug) is essentially a consensus algorithm.  I was playing with ideas in my head earlier, and my first version would be something like the following (tweaking as necessary based on real world performance):

1) Group the text into character-width streams for each encoding (potentially ignoring spaces)
2) Maintain a score for each candidate encoding.  For each character:
3) If it's a letter, +10 points
4) If it's a number, space, or punctuation, +5 points
5) If it's another valid character, +1 point
6) Otherwise -5 points.

Sum up the value for each encoding and divide each by the number of characters seen in that encoding's stream.  Pick the encoding with the highest score as the consensus and display that.
